name: Testing pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Install Google Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # Install ChromeDriver
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Verify Chrome & ChromeDriver Installation
      - name: Verify Chrome Installation
        run: |
          echo "Chrome version:"; google-chrome --version
          echo "ChromeDriver version:"; chromedriver --version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run TestNG Suite
        run: ./gradlew test -PsuitePath=src/test/resources/regressionSuiteForFlexTablePluginWithReport.xml --no-daemon

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: FlexTable-Extent-Report
          path: build/extendReportForFlexTablePlugin/Report.html
